### ISSUE TITLE
cannot build demo

### ISSUE THREAD

**Issue by gaming-hacker** [michaelarmstrong/SuperRecord#13]
hello,
the demo will not build.

error is 
SuperRecordDemo.xcodeproj cannot be opened because it is missing its project.pbxproj file.

xcode 6.1.1
iOS 8.1

**Comment by PGLongo** [comment]
I don't know why but the demo has been removed month ago by @michaelarmstrong.

**Comment by michaelarmstrong** [comment]
The demo was broken... I'll be updating it with a new and better sample project shortly. Until then, feel free to ask any questions.

**Comment by PGLongo** [comment]
I think it should be better have a small demo project inside this project and spent more time and effort on keeping updated a wiki and the Readme. 

In my opinion the only components that needs a demo project is **NSFetchedResultsControllerExtension**

**Comment by gaming-hacker** [comment]
that's ok, i just want to see it build and do something before spending hours integrating it.
