### ISSUE TITLE
Enable Travis

### ISSUE THREAD

**Issue by PGLongo** [michaelarmstrong/SuperRecord#19]
@michaelarmstrong  I have added Travis CI support, but I cannot change the settings of the repo so I can't enable the GitHub Webhook. It's very simple, follow this [instructions](http://docs.travis-ci.com/user/getting-started/).

Thanks

**Comment by michaelarmstrong** [comment]
Done. I also made a tiny commit to trigger the first build.

**Comment by PGLongo** [comment]
Perfect!
