### ISSUE TITLE
add the demo project with collection view

### ISSUE THREAD

**Issue by Javeru** [michaelarmstrong/SuperRecord#32]

**Comment by michaelarmstrong** [comment]
Is this something you'd like to undertake? or for someone else to complete?

**Comment by Javeru** [comment]
michaelarmstrong, сan you add examples to a project ?

**Comment by michaelarmstrong** [comment]
Sure, its something we've been meaning to do for a while. I'll try put a quick example together myself (will be a separate repo as i don't like including demo projects in a library project)... 

But i've tagged the issue "help wanted" in case anyone beats me to it :)

**Comment by PGLongo** [comment]
I think that the demo should be into the project, using the library with CocoaPods or Carthage (as recommended) you don't download the demo with the library.

**Comment by Javeru** [comment]
I'm rly wanna see collection view fetch results controller in action

**Comment by PGLongo** [comment]
I've started the demo project, a sort of Pokedex. I will add a table and the collection view.

Any other ideas?

**Comment by michaelarmstrong** [comment]
thats a great start, maybe use the SuperFetchedResultsController stuff and also put a welcome screen with some stats about the pokedex using the count() avg() etc stuff.
