### ISSUE TITLE
Swift 1.2

### ISSUE THREAD

**Issue by adamwaite** [michaelarmstrong/SuperRecord#34]
SuperRecord doesn't want to compile with the changes in Swift 1.2.

The major issue is the introduction of the failable cast `as!` over `as`, and there are some minor issues with optionality in CoreData and UIKit, and a few type checking issues too. I have to ship something before weekend, so I'll be working on this. Have you started any work on it yet? Or shall I just get stuck into it? 

Thanks

![screen shot 2015-04-15 at 09 12 48](https://cloud.githubusercontent.com/assets/1426233/7154769/53cf4428-e351-11e4-96e4-ef2934506309.png)

**Comment by michaelarmstrong** [comment]
SuperRecord 1.3 (released on the day of Swift 1.2 launch) should work with Swift 1.2, i'm using it in a project myself. Can you confirm you're on the latest version?

**Comment by PGLongo** [comment]
@adamwaite try to clean you DerivedData folder and then build the project again.

**Comment by PGLongo** [comment]
@adamwaite  I have just updated the version on CocoaPods, can you try again with the new version?

Thanks

**Comment by adamwaite** [comment]
New Cocoapods version works fine. Thanks!

**Comment by PGLongo** [comment]
Perfect! Thanks to you
